### ISSUE TITLE
Self is not released when gesture is added to Self itself.

### ISSUE THREAD

**Issue by karthikgs7** [RxSwiftCommunity/RxGesture#71] opened 2017-11-21 07:10 UTC
Self is not released when gesture is added to self itself. Have tried capturing self as weak and unowned, but no success. 

```
rx.pinchGesture()
            .asDriver()
            .skip(1)
            .drive(onNext: { [unowned self] recognizer in
                self.pinchGestureHandler(recognizer)
            })
            .disposed(by: rx.disposeBag)
```

Self is released when moving the subscription to superview of self.

```
imageView.rx.pinchGesture()
            .asDriver()
            .skip(1)
            .drive(onNext: { [unowned imageView] recognizer in
                imageView.pinchGestureHandler(recognizer)
            })
            .disposed(by: rx.disposeBag)
```

Wondering is this correct behavior or issue!

**Comment by 15538161133** [comment] 2017-11-26 08:48
11377185

**Comment by kaminisea** [comment] 2019-06-14 08:28
It may be solved already, but I reply 💪

What is the target of "not successful" is that 
"memory is not released" or "error occurs"? 🧐

It may be difficult to identify the cause that the memory
is not released because not a lot of information 😂

The cause of the error may be that you try to capture with unowned self,
the memory has already been released and an error has occurred.

So it might be better to capture with **[weak self]** 
and refer safely to the guard statement 🤟

**Comment by jegnux** [comment] 2019-06-14 12:34
Hum, actually I think i fixed that at some point. We should verify if it still happens.

**Comment by kaminisea** [comment] 2019-06-15 03:22
I have verified this issue.
As a result, I confirmed that memory leak does not occur now 👍
The verification contents will be the following with the [super view](https://github.com/catelina777/RxGesture-MemoryLeak-Test/blob/c6b95e7eb2ae6e0a8b0c0816787728563e4d6bdb/RxGesture-MemoryLeak-Test/Test1ViewController.swift#L14) and the [child view](https://github.com/catelina777/RxGesture-MemoryLeak-Test/blob/c6b95e7eb2ae6e0a8b0c0816787728563e4d6bdb/RxGesture-MemoryLeak-Test/TestImageView.swift#L14) 
-unowned self
-weak self
-use Binder

I also did verifications that cause circular references in the parent view and small views intentionally, and success to generate circular references as I aimed.

The repository I used for validation is [here](https://github.com/catelina777/RxGesture-MemoryLeak-Test)

Thank you as always 😂

**Comment by jegnux** [comment] 2019-06-15 07:44
Woah, thanks a lot @catelina777 👍 
I'm closing this issue then

**Closed as completed by jegnux** 2019-06-15 07:44 UTC
